### ISSUE TITLE
Install error for mmdet

### ISSUE THREAD

**Issue by kskim-phd** [i-pan/kaggle-rsna-pe#1]
Dear I-pan

Thanks for sharing the code.

When I try pip install -r requirements.txt, I got the following error.

ERROR: For --editable=/home/ianpan/anaconda3/envs/pytorch_p37_nt/lib/python3.7/site-packages/mmdet-1.1.0+1b299b5-py3.7.egg, only bzr+URL, git+URL, hg+URL, svn+URL are currently supported

Actually I do not have mmdet-1.1.0+1b299b5-py3.7.egg so could you share this file if it is required to run this code?

Thanks a lot.

**Comment by i-pan** [comment]
Hi. You actually do not need that package to run this code, so I removed that from the requirements.
